// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ship.proto

package planetexpress

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ship_FuelLevel int32

const (
	Ship_EMPTY Ship_FuelLevel = 0
	Ship_LOW   Ship_FuelLevel = 1
	Ship_FULL  Ship_FuelLevel = 2
)

var Ship_FuelLevel_name = map[int32]string{
	0: "EMPTY",
	1: "LOW",
	2: "FULL",
}

var Ship_FuelLevel_value = map[string]int32{
	"EMPTY": 0,
	"LOW":   1,
	"FULL":  2,
}

func (x Ship_FuelLevel) String() string {
	return proto.EnumName(Ship_FuelLevel_name, int32(x))
}

func (Ship_FuelLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_315cb18542033454, []int{0, 0}
}

type Ship struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location             string         `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	FuelLevel            Ship_FuelLevel `protobuf:"varint,3,opt,name=fuel_level,json=fuelLevel,proto3,enum=planetexpress.Ship_FuelLevel" json:"fuel_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Ship) Reset()         { *m = Ship{} }
func (m *Ship) String() string { return proto.CompactTextString(m) }
func (*Ship) ProtoMessage()    {}
func (*Ship) Descriptor() ([]byte, []int) {
	return fileDescriptor_315cb18542033454, []int{0}
}

func (m *Ship) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ship.Unmarshal(m, b)
}
func (m *Ship) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ship.Marshal(b, m, deterministic)
}
func (m *Ship) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ship.Merge(m, src)
}
func (m *Ship) XXX_Size() int {
	return xxx_messageInfo_Ship.Size(m)
}
func (m *Ship) XXX_DiscardUnknown() {
	xxx_messageInfo_Ship.DiscardUnknown(m)
}

var xxx_messageInfo_Ship proto.InternalMessageInfo

func (m *Ship) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ship) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Ship) GetFuelLevel() Ship_FuelLevel {
	if m != nil {
		return m.FuelLevel
	}
	return Ship_EMPTY
}

type GetShipResponse struct {
	Ship                 *Ship    `protobuf:"bytes,1,opt,name=ship,proto3" json:"ship,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShipResponse) Reset()         { *m = GetShipResponse{} }
func (m *GetShipResponse) String() string { return proto.CompactTextString(m) }
func (*GetShipResponse) ProtoMessage()    {}
func (*GetShipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_315cb18542033454, []int{1}
}

func (m *GetShipResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipResponse.Unmarshal(m, b)
}
func (m *GetShipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipResponse.Marshal(b, m, deterministic)
}
func (m *GetShipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipResponse.Merge(m, src)
}
func (m *GetShipResponse) XXX_Size() int {
	return xxx_messageInfo_GetShipResponse.Size(m)
}
func (m *GetShipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipResponse proto.InternalMessageInfo

func (m *GetShipResponse) GetShip() *Ship {
	if m != nil {
		return m.Ship
	}
	return nil
}

func init() {
	proto.RegisterEnum("planetexpress.Ship_FuelLevel", Ship_FuelLevel_name, Ship_FuelLevel_value)
	proto.RegisterType((*Ship)(nil), "planetexpress.Ship")
	proto.RegisterType((*GetShipResponse)(nil), "planetexpress.GetShipResponse")
}

func init() {
	proto.RegisterFile("ship.proto", fileDescriptor_315cb18542033454)
}

var fileDescriptor_315cb18542033454 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xce, 0xc8, 0x2c,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0xc8, 0x49, 0xcc, 0x4b, 0x2d, 0x49, 0xad,
	0x28, 0x28, 0x4a, 0x2d, 0x2e, 0x56, 0x9a, 0xcf, 0xc8, 0xc5, 0x12, 0x9c, 0x91, 0x59, 0x20, 0x24,
	0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b,
	0x49, 0x71, 0x71, 0xe4, 0xe4, 0x27, 0x27, 0x96, 0x64, 0xe6, 0xe7, 0x49, 0x30, 0x81, 0xc5, 0xe1,
	0x7c, 0x21, 0x1b, 0x2e, 0xae, 0xb4, 0xd2, 0xd4, 0x9c, 0xf8, 0x9c, 0xd4, 0xb2, 0xd4, 0x1c, 0x09,
	0x66, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x59, 0x3d, 0x14, 0xc3, 0xf5, 0x40, 0x06, 0xeb, 0xb9, 0x95,
	0xa6, 0xe6, 0xf8, 0x80, 0x14, 0x05, 0x71, 0xa6, 0xc1, 0x98, 0x4a, 0x9a, 0x5c, 0x9c, 0x70, 0x71,
	0x21, 0x4e, 0x2e, 0x56, 0x57, 0xdf, 0x80, 0x90, 0x48, 0x01, 0x06, 0x21, 0x76, 0x2e, 0x66, 0x1f,
	0xff, 0x70, 0x01, 0x46, 0x21, 0x0e, 0x2e, 0x16, 0xb7, 0x50, 0x1f, 0x1f, 0x01, 0x26, 0x25, 0x2b,
	0x2e, 0x7e, 0xf7, 0xd4, 0x12, 0x90, 0x51, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42,
	0xea, 0x5c, 0x2c, 0x20, 0x1f, 0x81, 0xdd, 0xca, 0x6d, 0x24, 0x8c, 0xc5, 0xd6, 0x20, 0xb0, 0x02,
	0x27, 0xe1, 0x28, 0xc1, 0x82, 0xec, 0x74, 0x7d, 0x14, 0xf9, 0x24, 0x36, 0x70, 0x40, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xbf, 0x16, 0xbd, 0x16, 0x01, 0x00, 0x00,
}
